- www/kubl05/index.html
> Zkouška spojení z domova

- www/hodl01/cv.html
> Inicializační commit

- www/shia02/index.html
> PRIDALA JSEM INDEX.HTML

- www/havm10/index.html
- www/havm10/resume.html
Žádám úvodní potvrzení, přidávám úvodní úkol
> Student havm10

- www/kukd01/blog.html
- www/kukd01/cheatsheat.html
- www/kukd01/resume.html
Založení Gitu a nahrání prvních souborů
> Student kukd01

- guide-git/README.md
- www/polj10/test.html
Oprava guide-git a test pull requestu.
> Student polj10

- www/kubl05/blog.html
- www/kubl05/cheatsheet.html
- www/kubl05/firma.html
- www/kubl05/index.html
- www/kubl05/resume.html
Hotový domácí úkol (úvodní stránka pro web firmy) se nachází v souboru firma.html.
+pár kosmetických vylepšení předchozích stránek
> Domácí úkol

- www/klei00/index.html
Domácí úkol - úvodní stránka firmy
> Student klei00

- www/kubl05/firma.html
K produktům přidány buttoníky.
> Domácí úkol v3

- www/klei00/index.html
> Buttons added

- www/barp08/W1/CV_Gates.html
- YT videos are now opened in new tabs
- "Go to Microsoft" button overhaul
> barp08 - bug fixes

- www/hodl01/company.html
odevzdávám domací úkol ze 3.cvika.
> Company page- domaci ukol z cv3

- www/blak05/index.html
rád bych už něco viděl na stránkách https://fcp.vse.cz/... a zjistil jestli jsem vše nastavil správně
> nahrani prvniho souboru

- www/zemk05/cv3-ukol/index.html
> index created

- www/novj35/resume.html
> Zmena nadpisu

- www/klaj01/resume.html
Nahrání prvního souboru - resume.html
> Nahrání prvního souboru

- www/khur00/1cviko.html
> Student khur00

- www/havm10/ukol2.html
Dobrý den, posílám request ohledně druhého úkolu
> odevzdání druhého úkolu

- www/horj18/firma/index.html
- www/horj18/index.html
> Student horj18

- www/janf04/firma.html
Přehodil jsem navigaci do headeru a automaticky naformátoval kód
> navigace přehozena do headeru

- www/bust01/Uvodni_stranka_webu_Domaci_Ukol.html
- www/bust01/css/index-styly.css
- www/bust01/css/resume-styly.css
- www/bust01/css/task-styly.css
- www/bust01/index.html
- www/bust01/resume.html
- www/bust01/task.html
Styly pro celkovou stránku (*) se mi někam poděly, nevím jaktože tam nebyly. Ostatní jsem upravil, ačkoliv tabulku se základními informacemi jsem prostě bral jako tabulku, kde jsem původně měl i Jméno, Adresa, v prvním sloupečku, což jsem nakonec smazal. Tudíž to nebylo jen kvůli rozložení stránky, jak jste se domníval. Každopádně jsem to upravil.
Nevím, jak upravovat původní pull request, proto vytvářím nový.
> Úprava domácího úkolu

- www/shia02/du3.html
- www/shia02/du3_styles.css
- www/shia02/resume.html
- www/shia02/resume_styles.css
> Student shia02

- www/klei00/hw3/index.html
- www/klei00/hw3/styles/style.css
> Homework 3

- www/blak05/hw4/grid.html
- www/blak05/hw4/page-layout.html
- www/blak05/hw4/style-page-layout.css
- www/blak05/hw4/styles-grid.css
oba dva dokumenty (+ jejich externí css) jsem nahrál najednou
> Nahrávám úkol č.4

- www/kast00/ukol4/css/styles-grid.css
- www/kast00/ukol4/css/styles-page-layout.css
- www/kast00/ukol4/task-grid.html
- www/kast00/ukol4/task-page-layout.html
> Student kast00

- www/litv00/du3_css_litv00.css
- www/litv00/du3_litv00.html
> treti domaci ukol

- www/ujhl00/homework_css/homework_04/styles-grid.css
- www/ujhl00/homework_css/homework_04/styles-page-layout.css
- www/ujhl00/homework_css/homework_04/task-grid.html
- www/ujhl00/homework_css/homework_04/task-page-layout.html
- www/ujhl00/homework_css/resume/styles.css
- www/ujhl00/week5_company/css/styles.css
- www/ujhl00/week6/spinner/spiner.html
- www/ujhl00/week6/spinner/spinner.css
> Student ujhl00

- www/kubl05/SP1/about.html
- www/kubl05/SP1/career.html
- www/kubl05/SP1/contact.html
- www/kubl05/SP1/css/styles.css
- www/kubl05/SP1/index.html
- www/kubl05/SP1/inspiration.html
- Sloučen css link v head
- Opraven span bug
- Úprava velikostí v printu
> Oprava chyb

- www/janf04/ukol 4/css/styles-grid.css
- www/janf04/ukol 4/css/styles-page-layout.css
- www/janf04/ukol 4/task-grid.html
- www/janf04/ukol 4/task-page-layout.html
> vypracovaný úkol 4

- www/havm10/StaticPage/circles.html
- www/havm10/StaticPage/css/styles.css
- www/havm10/StaticPage/education.html
- www/havm10/StaticPage/home.html
- www/havm10/StaticPage/nonEducation.html
- www/havm10/StaticPage/other.html
Odevzdání statických stránek (první semestrální práce)
> odevzdáni statickych stranek

- www/kubl05/SP1/css/styles.css
Tak doufám, že už se to zalamování neděje.
> Header bug fix

- www/klei00/semester_project_1/index.html
- www/klei00/semester_project_1/price_list.html
- www/klei00/semester_project_1/styles/main.css
Takhle už jsou ta tlačítka v pořádku?
> Seminární práce 1

- www/havm10/homework-05/JavaScript.html
- www/havm10/homework-05/js/main.js
> pridani 5 ukolu

- www/klei00/homework-05/js/main.js
> HW5 corrections

- www/horj18/staticky_web/index.html
- www/horj18/staticky_web/kontakt.html
- www/horj18/staticky_web/koralky.html
- www/horj18/staticky_web/o_mne.html
- www/horj18/staticky_web/pet.html
- www/horj18/staticky_web/polymer.html
- www/horj18/staticky_web/style.css
- www/horj18/staticky_web/swarovski.html
- www/horj18/staticky_web/vyrobky.html
Jenom doplněny texty a minor bug zobrazení na mobilu
> Texty + minor fixes

- www/janf04/semestralka1/fotogalerie.html
- www/janf04/semestralka1/hraci.html
- www/janf04/semestralka1/index.html
- www/janf04/semestralka1/oklubu.html
- www/janf04/semestralka1/zapasy.html
jen obaleno mainem, jsem ready na hodnocení
> main added + hodnocení

- www/ujhl00/project1/main.css
Ešte som niečo upravil, takže snáď finálny pullrequest.
> column menu

- www/barp08/S1/aboutme.html
- www/barp08/S1/blog.html
- www/barp08/S1/contact.html
- www/barp08/S1/css/styles.css
- www/barp08/S1/index.html
- www/barp08/S1/projects.html
- upraven media screen
- gramatika, zkraceni nazvu jednotlivych tabs
> S1 bug fixes

- www/benj12/sp1/index.html
Prosim o ohodnocení práce, díky :)
> I. semestralni prace - beze zmen

- www/havm10/homework 07/css/main.css
- www/havm10/homework 07/index.html
- www/havm10/homework 07/js/main.js
Odevzdávám úkol 7 (aplikace pexeso)
> odevzdání úkolu 7

- www/zemk05/Domácí úkoly/homework-07/css/styles.css
- www/zemk05/Domácí úkoly/homework-07/index.html
- www/zemk05/Domácí úkoly/homework-07/js/main.js
> Homework 7 - první verze

- www/kubl05/homework-07/index.html
- www/kubl05/homework-07/main.css
- www/kubl05/homework-07/main.js
Až později jsem si všiml, že v zadání je hláška o výhře, nezáporný počet bodů atd.. Upraveno
> Úkol numero 7

- www/xyerv00/homework-05/index.html
- www/xyerv00/homework-05/main.js
o body si nanárokuji, spíš jsem si to chtěla dodělat pro procvičení
> homework-05

- www/dusv03/homework-07/css/main.css
- www/dusv03/homework-07/js/main.js
- www/dusv03/homework-08/css/main.css
- www/dusv03/homework-08/index.html
- www/dusv03/homework-08/js/app.js
Prosím ani nehodnotit, za prvé odevzdávám pozdě a za druhé jsem vzal kód přímo z řešení. Nevěděl jsem si s řešením rady a tak jsem akorát prošel kód, abych pochopil, jak funguje. V tomhle případě asi ani nebyl potřeba pull request.
> domácí úkol 8 + dodatečné úpravy úkolu 7

- www/klaj01/SP2/css/stylesheet.css
- www/klaj01/SP2/index.html
- www/klaj01/homework-08/css/stylesheet.css
- www/klaj01/homework-08/index.html
- www/klaj01/homework-08/js/script.js
HW-08 : Zatím bohužel jen část úkolu
> HW-08 : Zakladni stylovani + cast JS

- www/dusv03/SP2/css/main.css
- www/dusv03/SP2/index.html
- www/dusv03/SP2/js/main.js
Základní adresářová struktura bez obsahu
> 2SP - úvodní commit

- www/stos02/API Youtube/inex.html
- www/stos02/API Youtube/main.css
- www/stos02/API Youtube/main.js
> API YouTube

- www/dust01/TempoFoxies/css/materialize.css
- www/dust01/TempoFoxies/historie.html
- www/dust01/TempoFoxies/index.html
- www/dust01/TempoFoxies/kontakty.html
- www/dust01/TempoFoxies/login.html
- www/dust01/TempoFoxies/main.css
- www/dust01/TempoFoxies/main.js
- www/dust01/TempoFoxies/registrace.html
- www/dust01/TempoFoxies/soutez.html
- www/dust01/TempoFoxies/teams.html
- www/dust01/homework-05/JavaScriptexercise.html
- www/dust01/homework-05/main.js
> Student dust01
